nome = str(input('Digite seu nome: '))
print('O nome padrao é esse: {}'.format(nome))
ma = nome.upper()
print(ma)
me = nome.lower()
print(me)
nl = len(nome)-nome.count(' ')
print('total de letras é {}'.format(nl))
ql = nome.find(" ")
print('Quantidades de letras no  primeiro nome: {}'.format(ql))